#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: concourse-petclinic
type: Opaque
data:
  harborDomain: #@ base64.encode(data.values.common.harborDomain)
  harborUser: #@ base64.encode(data.values.common.harborUser)
  harborPassword: #@ base64.encode(data.values.common.harborPassword)
  kubeconfigBuildServer: #@ base64.encode(data.values.common.kubeconfigBuildServer)
  kubeconfigAppServer: #@ base64.encode(data.values.common.kubeconfigAppServer)
  concourseHelperImage: #@ base64.encode(data.values.common.concourseHelperImage)
  githubUser: #@ base64.encode(data.values.common.githubUser)
  githubToken: #@ base64.encode(data.values.common.githubToken)
  awsAccessKeyId: #@ base64.encode(data.values.common.awsAccessKeyId)
  awsSecretAccessKey: #@ base64.encode(data.values.common.awsSecretAccessKey)
  awsRegion: #@ base64.encode(data.values.common.awsRegion)
  
  
