#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: concourse-petclinic
type: Opaque
data:
  harborDomain: #@ base64.encode(data.values.commonSecrets.harborDomain)
  harborUser: #@ base64.encode(data.values.commonSecrets.harborUser)
  harborPassword: #@ base64.encode(data.values.commonSecrets.harborPassword)
  kubeconfigBuildServer: #@ base64.encode(data.values.commonSecrets.kubeconfigBuildServer)
  kubeconfigAppServer: #@ base64.encode(data.values.commonSecrets.kubeconfigAppServer)
  concourseHelperImage: #@ base64.encode(data.values.commonSecrets.concourseHelperImage)
  githubUser: #@ base64.encode(data.values.commonSecrets.githubUser)
  githubToken: #@ base64.encode(data.values.commonSecrets.githubToken)
  awsAccessKeyId: #@ base64.encode(data.values.commonSecrets.awsAccessKeyId)
  awsSecretAccessKey: #@ base64.encode(data.values.commonSecrets.awsSecretAccessKey)
  awsRegion: #@ base64.encode(data.values.commonSecrets.awsRegion)
  
  
