#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---  
apiVersion: v1
kind: Secret
metadata:
  name: petclinic
  namespace: concourse-petclinic
type: Opaque
data:
  host: #@ base64.encode(data.values.petclinic.host)
  stagingPrefix: #@ base64.encode(data.values.petclinic.stagingPrefix)
  stagingDomain: #@ base64.encode(data.values.petclinic.stagingDomain)
  image: #@ base64.encode(data.values.petclinic.image)
  tbsNamespace: #@ base64.encode(data.values.petclinic.tbs.namespace)
  wavefrontApplicationName: #@ base64.encode(data.values.petclinic.wavefront.applicationName)
  wavefrontUri: #@ base64.encode(data.values.petclinic.wavefront.uri)
  wavefrontApiToken: #@ base64.encode(data.values.petclinic.wavefront.apiToken)
  wavefrontDeployEventName: #@ base64.encode(data.values.petclinic.wavefront.deployEventName)
  configRepo: #@ base64.encode(data.values.petclinic.configRepo)
  codeRepo: #@ base64.encode(data.values.petclinic.codeRepo)
  packageRepo: #@ base64.encode(data.values.petclinic.packageRepo)
  packageGroup: #@ base64.encode(data.values.petclinic.packageGroup)
