#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube
  namespace: concourse-petclinic
type: Opaque
data:
  host: #@ base64.encode(data.values.sonarqube.host)
  token: #@ base64.encode(data.values.sonarqube.token)
  resultsBucket: #@ base64.encode(data.values.sonarqube.resultsBucket)
  adminPassword: #@ base64.encode(data.values.sonarqube.adminPassword)
  databasePassword: #@ base64.encode(data.values.sonarqube.databasePassword)